# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ordmeta_mono <- function(p) {
    .Call('_metapro_ordmeta_mono', PACKAGE = 'metapro', p)
}

ordmeta_signed <- function(p, effect_size, sort_by_decreasing = TRUE) {
    .Call('_metapro_ordmeta_signed', PACKAGE = 'metapro', p, effect_size, sort_by_decreasing)
}

